
#define SCPI_MAX_INPUT_BUFFER_LEN 128
#define SCPI_MAX_RESPONSE_LEN 128
#define SCPI_MAX_PARAM_LEN 5
#define SCPI_MAX_TOKENS 30
#define SCPI_MAX_COMMANDS 5
#define SCPI_MAX_RET_LEN 10
#define SCPI_MAX_TOKEN_LEN 15
